### ISSUE TITLE
using axios-curlirize on node app

### ISSUE THREAD

**Issue by darekzak** [delirius325/axios-curlirize#20]
Hi, 
I tried to use this in node app but it gives me an error
```
node_modules/axios-curlirize/src/curlirize.js:1
import { CurlHelper } from './lib/CurlHelper';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:811:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)

```

Not sure what's going on. Is is suppose to work only in js engine that supports es modules?

**Comment by delirius325** [comment]
Mmmh, this is strange... When installing the module via `npm` or `yarn` the `postinstall` script should compile the package in native JavaScript (instead of ECMAScript 2016). Therefore the code that your app would be importing should be `node_modules/axios-curlirize/dist/curilirize.js`. 

Let me look into this.

**Comment by delirius325** [comment]
I have released version `1.3.2`. Please update and see if you still are experiencing issues. Thanks

**Comment by darekzak** [comment]
I checked and still doesn't work. After installing this package with yarn(and also I checked with npm)  inside node_modules/axios-curlirize there is no dist directory. I checked this on completely fresh project. There is no node_modules directory inside node_modules/axios-curlirize - so there is no babel. Postinstall script because of this doesn't  do anything - at least this is how I understand it.

**Comment by delirius325** [comment]
I find this pretty weird as CircleCI does show that the postinstall script is working and compiling the the package

**Comment by darekzak** [comment]
It works now. Thanks for changes.

**Comment by shaheerizharReal** [comment]
Experiencing same issue in 1.3.7

**Comment by shesl-meow** [comment]
Experiencing same issue in 1.4.0

**Comment by skliarovartem** [comment]
Same problem...
